<?php
return [
  'button' => '<button{{attrs}}>{{text}}</button>',
  'checkbox' => '<input type="checkbox" name="{{name}}" value="{{value}}"{{attrs}}>',
  'checkboxFormGroup' => '{{label}}',
  'checkboxWrapper' => '<div class="checkbox">{{label}}</div>',
  'dateWidget' => '<div class="form-control">{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}{{meridian}}</div>',
  'error' => '<div class="error-message">{{content}}</div>',
  'errorList' => '<ul>{{content}}</ul>',
  'errorItem' => '<li>{{text}}</li>',
  'file' => '<input type="file" name="{{name}}"{{attrs}}>',
  'fieldset' => '<fieldset{{attrs}}>{{content}}</fieldset>',
  'formStart' => '<form{{attrs}}>',
  'formEnd' => '</form>',
  'formGroup' => '{{label}}{{input}}',
  'hiddenBlock' => '<div style="display:none;">{{content}}</div>',
  'input' => '<input type="{{type}}" name="{{name}}"{{attrs}}/>',
  'inputSubmit' => '<input type="{{type}}"{{attrs}}/>',
  'inputContainer' => '<div class="input form-group {{type}}{{required}}">{{content}}</div>',
  'inputContainerError' => '<div class="input form-group {{type}}{{required}} error">{{content}}{{error}}</div>',
  'label' => '<label{{attrs}}>{{text}}</label>',
  'nestingLabel' => '{{hidden}}<label{{attrs}}>{{input}}{{text}}</label>',
  'legend' => '<legend>{{text}}</legend>',
  'multicheckboxTitle' => '<legend>{{text}}</legend>',
  'multicheckboxWrapper' => '<fieldset{{attrs}}>{{content}}</fieldset>',
  'option' => '<option value="{{value}}"{{attrs}}>{{text}}</option>',
  'optgroup' => '<optgroup label="{{label}}"{{attrs}}>{{content}}</optgroup>',
  'select' => '<select name="{{name}}"{{attrs}}>{{content}}</select>',
  'selectMultiple' => '<select name="{{name}}[]" multiple="multiple"{{attrs}}>{{content}}</select>',
  'radio' => '<input type="radio" name="{{name}}" value="{{value}}"{{attrs}}>',
  'radioWrapper' => '{{label}}',
  'textarea' => '<textarea name="{{name}}"{{attrs}}>{{value}}</textarea>',
  'submitContainer' => '<div class="submit">{{content}}</div>',
];
